# -*- coding: utf-8 -*-
"""problema_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qa4OAOhgxOzWO8Za6kcA1hyDOlNSi5ms
"""

import math
from multiprocessing import Process, Array

N = 21  # Número total de términos en la serie
M = 4   # Número de vectores (procesadores)

def generar_serie(start, end, vector):
    for i in range(start, end):
      if(i<=N):
        vector[i - start] = (i) * 2

if __name__ == "__main__":
    terms_per_vector = math.ceil(N / M) # Número de términos por vector
    vectors = [Array('i', [0] * terms_per_vector) for _ in range(M)]  # Vectores para almacenar los términos

    processes = []
    for i in range(M):
        start_term = i * terms_per_vector + 1
        end_term = (i + 1) * terms_per_vector + 1
        process = Process(target=generar_serie, args=(start_term, end_term, vectors[i]))
        processes.append(process)

    for process in processes:
        process.start()

    for process in processes:
        process.join()

    # Imprimir los términos de cada vector
    print("Términos en los vectores:")
    for i, vector in enumerate(vectors):
        print(f"Vector {i}: {list(vector)}")